version: v2
    
tasks:    
  build-image:
    variables:
    - HELM_CHART=php-app/
    steps:
    - checkout
    - commands: 
      - helm lint $HELM_CHART
    - docker/build:
        image: saurabh3460/php-app
        tags: ["latest", "${CI_COMMIT_SHA:0:8}"]
        push: true
    - workspace/persist:
        paths: [php-app]

  deploy:
    depends: [build-image]
    variables:
    - APP_NAME=php-app
    - DOCKER_TAG=${CI_COMMIT_SHA:0:8}
    - HELM_CHART=php-app/
    - NS=app
    steps:
    - workspace/attach
    - commands:
      - |
        helm dep up $HELM_CHART
        helm upgrade --install --reuse-values $APP_NAME $HELM_CHART \
          --set image.tag=$DOCKER_TAG 
trigger:
  when: branch in ("main","stage", "prod")